sudo: required
services:
  - docker

before_install:
  - docker build -t slick3gz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run slick3gz/react-test npm test -- --coverage

after_success:
  - docker build -t slick3gz/multi-client ./client
  - docker build -t slick3gz/multi-nginx ./nginx
  - docker build -t slick3gz/multi-server ./server
  - docker build -t slick3gz/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub
  - docker push slick3gz/multi-client
  - docker push slick3gz/multi-nginx
  - docker push slick3gz/multi-server
  - docker push slick3gz/multi-worker
